#
# Module manifest for module 'task4DSC'
#
# Generated by: Aliaksandra_Navitska
#
# Generated on: 1/20/2018
#

@{

# Version number of this module.
ModuleVersion = '1.4.0'

# ID used to uniquely identify this module
GUID = 'b2a06004-4832-4072-8399-0fa47667957c'

# Author of this module
Author = 'Aliaksandra_Navitska'

# Company or vendor of this module
CompanyName = 'My Company'

# Copyright statement for this module
Copyright = '(c) 2018 Aliaksandra_Navitska. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This is a composite DSC resource created as Azure Automation module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @( 'IISInstallConfiguration' )

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Usagich/azure-training/tree/master/task4'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

