#
# Module manifest for module 'xTaskCompo'
#
# Generated by: Aliaksandra_Navitska
#
# Generated on: 1/20/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IISInstallConfiguration.schema.psm1'

# Version number of this module.
ModuleVersion = '0.4.0'

# ID used to uniquely identify this module
GUID = '0031cc89-c9d0-4bf5-b8d9-b2896cfdcb22'

# Author of this module
Author = 'Aliaksandra_Navitska'

# Company or vendor of this module
CompanyName = 'My Corporation'

# Copyright statement for this module
Copyright = '(c) 2018 Aliaksandra_Navitska. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Configuration for installing IIS role and configuring a binding to the port 8080.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

}